language: python
python:
- 2.7
- pypy
install:
- python setup.py install
script:
- nosetests ztag
- ztag -t
sudo: false
notifications:
  email:
  - team@censys.io
  slack:
    secure: HQHCPazu4ThXRVGL2coYf/Pakbwy6kD0va6SUkIJPZ4QDjFridCPkvG/4M0LWdMGwNutaPlVLPypP1hU9jHoxaY2wB4qH8/WDp4SADus8TWvSkVaP6mzBz+yB1szX5mT/z7DpD3P26LqqdktxYB94hGl2zgQfANL7ur69hSk5To=
